const EMAIL='melissasteele462@outlook.com';
const enc=s=>encodeURIComponent(s||'');
const menu=document.querySelector('.menu'),tog=document.querySelector('.toggle');
if(tog)tog.addEventListener('click',()=>{let open=menu.classList.toggle('open');tog.setAttribute('aria-expanded',String(open));});
function collect(f){let d=new FormData(f),g={},lines=[];for(const [k,v] of d.entries()){let c=String(v).trim();if(!c)continue;(g[k]||(g[k]=[])).push(c);}lines.push(f.dataset.name||'MADF WorldWide Form');lines.push('Submitted from: '+location.href);lines.push('Date: '+new Date().toLocaleString());lines.push('----------------------------------------');Object.entries(g).forEach(([k,v])=>lines.push(k+': '+v.join(', ')));return lines.join('\n');}
async function copy(t){try{await navigator.clipboard.writeText(t);alert('Copied to clipboard.');}catch(e){alert('Copy not available. Select the preview text and copy it manually.');}}
document.querySelectorAll('form.smart').forEach(f=>{f.addEventListener('submit',e=>{e.preventDefault();let b=collect(f),o=f.querySelector('output');if(o){o.textContent=b+'\n\nSend to: '+EMAIL;o.classList.add('show');}let url='mailto:'+EMAIL+'?subject='+enc(f.dataset.subject||'MADF WorldWide Website Form')+'&body='+enc(b);if(url.length>1800){alert('Your form is detailed. Copy the preview text and email it to Melissa Steele.');}else{location.href=url;}});let c=f.querySelector('[data-copy]');if(c)c.addEventListener('click',()=>copy(collect(f)));});
const title='MADF WorldWide recruitment agency',text='Apply for recruitment, sourcing, sales and staffing opportunities with MADF WorldWide.',pageUrl='https://madf-worldwide.github.io/MADF-Staffing-Solutions/';
document.querySelectorAll('[data-share]').forEach(a=>{let m={linkedin:'https://www.linkedin.com/sharing/share-offsite/?url='+enc(pageUrl),facebook:'https://www.facebook.com/sharer/sharer.php?u='+enc(pageUrl),x:'https://twitter.com/intent/tweet?text='+enc(text)+'&url='+enc(pageUrl),whatsapp:'https://wa.me/?text='+enc(text+' '+pageUrl),email:'mailto:?subject='+enc(title)+'&body='+enc(text+'\n\n'+pageUrl)};a.href=m[a.dataset.share]||pageUrl;if(a.dataset.share!=='email'&&a.dataset.share!=='whatsapp')a.target='_blank';a.rel='noopener';});
document.querySelectorAll('[data-native]').forEach(b=>b.addEventListener('click',async()=>{if(navigator.share)await navigator.share({title:title,text:text,url:pageUrl});else copy(text+' '+pageUrl);}));
